apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
spec:
  clusterIP: None  # Headless Service: StatefulSet Pod 직접 접근 가능
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
