apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: default
spec:
  type: ClusterIP  # 클러스터 내부 통신용, NodePort/LoadBalancer로 변경 가능
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80        # 클러스터 내부에서 접근할 포트
      targetPort: 8080  # Pod 컨테이너 포트
